const SECONDS_IN_ONE_MINUTE = 60 as const;
const MINUTES_IN_ONE_HOURS = 60 as const;
const HOURS_IN_ONE_DAY = 24 as const;

const SECONDS_IN_ONE_HOUR = SECONDS_IN_ONE_MINUTE * MINUTES_IN_ONE_HOURS
const SECONDS_IN_ONE_DAY = SECONDS_IN_ONE_HOUR * HOURS_IN_ONE_DAY

export {
  SECONDS_IN_ONE_MINUTE,
  MINUTES_IN_ONE_HOURS,
  HOURS_IN_ONE_DAY,
  SECONDS_IN_ONE_HOUR,
  SECONDS_IN_ONE_DAY,
}